CONFIG:
  RANDOM_MOB_SPAWN: 1000
  RANDOM_SPAWNER_DROP: 100
  # Item in Hand to drop a Spawner
  SPAWNER_BREAK:
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE
  # Enchantment
  SPAWNER_ENCHANTMENT:
    - SILK_TOUCH
  BLACKLIST:
    - PLAYER
    - WITHER_SKELETON